# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(722, 394)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 701, 61))
        self.frame_2.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border: 5px solid black;\n"
"border-radius: 20px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius:0px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.minimize_bt = QtWidgets.QPushButton(self.frame_2)
        self.minimize_bt.setGeometry(QtCore.QRect(590, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.minimize_bt.setFont(font)
        self.minimize_bt.setStyleSheet("QPushButton#minimize_bt {\n"
"    background-color: transparent;\n"
"    color: rgb(52, 107, 1);\n"
"    border: 5px solid rgb(52, 107, 1);\n"
"    border-radius: 5px\n"
"    }\n"
"QPushButton#minimize_bt::hover {\n"
"    background-color: green\n"
"    }")
        self.minimize_bt.setObjectName("minimize_bt")
        self.close_bt = QtWidgets.QPushButton(self.frame_2)
        self.close_bt.setGeometry(QtCore.QRect(640, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.close_bt.setFont(font)
        self.close_bt.setStyleSheet("QPushButton#close_bt { \n"
"    background-color: transparent; \n"
"    color: rgb(166, 0, 0);\n"
"     border: 5px solid rgb(166, 0, 0);\n"
"    border-radius: 5px\n"
"    }\n"
"\n"
"QPushButton#close_bt::hover {\n"
"    background-color: red;\n"
"    }")
        self.close_bt.setObjectName("close_bt")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(110, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"border: 0")
        self.label.setObjectName("label")
        self.icon = QtWidgets.QLabel(self.frame_2)
        self.icon.setGeometry(QtCore.QRect(10, 0, 81, 71))
        self.icon.setStyleSheet("border:0; background-color: transparent")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("graphic/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setWordWrap(True)
        self.icon.setObjectName("icon")
        self.treeWidget = QtWidgets.QTreeWidget(Form)
        self.treeWidget.setGeometry(QtCore.QRect(5, 71, 711, 321))
        self.treeWidget.setStyleSheet("QTreeWidget {\n"
"    background-color: black;\n"
"    font: 75 14pt \"MS Shell Dlg 2\";\n"
"    }\n"
"QTreeWidget::item{\n"
"    border: 2px solid white;\n"
"    border-radius:5px;\n"
"    background-color: rgba(255, 255, 255, 200);\n"
"    color: black;\n"
"    padding-left: 10px\n"
"}\n"
"\n"
"QTreeWidget::item:selected{\n"
"    background-color: rgba(175, 175, 175, 100);\n"
"    border: 2px solid red\n"
"}\n"
"\n"
"\n"
"QTreeWidget::item:!selected{\n"
"    background-color:rgba(0, 0, 0, 10);\n"
"    color: white\n"
"}")
        self.treeWidget.setObjectName("treeWidget")
        self.treeWidget.headerItem().setTextAlignment(0, QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.treeWidget.headerItem().setFont(0, font)
        self.treeWidget.headerItem().setBackground(0, QtGui.QColor(191, 191, 191))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.treeWidget.headerItem().setForeground(0, brush)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_2 = QtWidgets.QTreeWidgetItem(item_1)
        self.add_account = QtWidgets.QPushButton(Form)
        self.add_account.setGeometry(QtCore.QRect(590, 350, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(14)
        self.add_account.setFont(font)
        self.add_account.setStyleSheet("QPushButton#add_account{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton#add_account::hover{\n"
"    background-color: gray;\n"
"    }4")
        self.add_account.setObjectName("add_account")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.minimize_bt.setText(_translate("Form", "_"))
        self.close_bt.setText(_translate("Form", "X"))
        self.label.setText(_translate("Form", "PASSManager"))
        self.treeWidget.headerItem().setText(0, _translate("Form", "accounts"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("Form", "google"))
        self.treeWidget.topLevelItem(0).child(0).setText(0, _translate("Form", "email"))
        self.treeWidget.topLevelItem(0).child(0).child(0).setText(0, _translate("Form", "password"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.add_account.setText(_translate("Form", "+Add Account"))

if __name__ == '__main__':
        import sys
        app = QtWidgets.QApplication(sys.argv)
        window = Ui_Form()
        Form = QtWidgets.QWidget()
        window.setupUi(Form)
        Form.show()
        sys.exit(app.exec_())