# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(453, 514)
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(0, 10, 451, 61))
        self.frame.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border: 5px solid black;\n"
"border-radius: 20px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius:0px")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.minimize_bt = QtWidgets.QPushButton(self.frame)
        self.minimize_bt.setGeometry(QtCore.QRect(340, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.minimize_bt.setFont(font)
        self.minimize_bt.setStyleSheet("QPushButton#minimize_bt {\n"
"    background-color: transparent;\n"
"    color: rgb(52, 107, 1);\n"
"    border: 5px solid rgb(52, 107, 1);\n"
"    border-radius: 5px\n"
"    }\n"
"QPushButton#minimize_bt::hover {\n"
"    background-color: green\n"
"    }")
        self.minimize_bt.setObjectName("minimize_bt")
        self.close_bt = QtWidgets.QPushButton(self.frame)
        self.close_bt.setGeometry(QtCore.QRect(390, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.close_bt.setFont(font)
        self.close_bt.setStyleSheet("QPushButton#close_bt { \n"
"    background-color: transparent; \n"
"    color: rgb(166, 0, 0);\n"
"     border: 5px solid rgb(166, 0, 0);\n"
"    border-radius: 5px\n"
"    }\n"
"\n"
"QPushButton#close_bt::hover {\n"
"    background-color: red;\n"
"    }")
        self.close_bt.setObjectName("close_bt")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(70, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"border: 0")
        self.label.setObjectName("label")
        self.icon = QtWidgets.QLabel(self.frame)
        self.icon.setGeometry(QtCore.QRect(20, 10, 41, 41))
        self.icon.setStyleSheet("border:0")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("graphic/login.png"))
        self.icon.setScaledContents(True)
        self.icon.setWordWrap(True)
        self.icon.setObjectName("icon")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setGeometry(QtCore.QRect(0, 73, 451, 431))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Rockwell Extra Bold")
        font.setPointSize(20)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"    border: 1px solid white;\n"
"    border-top: 0;\n"
"    background: black;\n"
"}\n"
"\n"
"QTabBar::tab{\n"
"    background: black;\n"
"    color: white;\n"
"    border: 3px solid white;\n"
"    border-bottom: 0;\n"
"    border-radius: 5px;\n"
"    width: 218px\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    background: white;\n"
"    color: black;\n"
"    border: 3px solid silver\n"
"    }\n"
"    \n"
"QTabBar::tab:!selected:hover {\n"
"    background: gray;\n"
"}\n"
"")
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setElideMode(QtCore.Qt.ElideNone)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.widget = QtWidgets.QWidget(self.tab)
        self.widget.setGeometry(QtCore.QRect(6, 12, 431, 371))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: white")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.username = QtWidgets.QLineEdit(self.widget)
        self.username.setMinimumSize(QtCore.QSize(18, 0))
        self.username.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username.setFont(font)
        self.username.setStyleSheet("border: 5px solid white; color: white; background-color: transparent")
        self.username.setText("")
        self.username.setObjectName("username")
        self.horizontalLayout_2.addWidget(self.username)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: white")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.password = QtWidgets.QLineEdit(self.widget)
        self.password.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password.setFont(font)
        self.password.setStyleSheet("border: 5px solid white; color: white; background-color: transparent")
        self.password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password.setObjectName("password")
        self.horizontalLayout.addWidget(self.password)
        self.pushButton = QtWidgets.QPushButton(self.widget)
        self.pushButton.setStyleSheet("background-color:transparent;\n"
"border: 3px solid white;\n"
"border-radius: 10px")
        self.pushButton.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("graphic/hide_pass.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("graphic/hide_pass.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("graphic/show_pass.png"), QtGui.QIcon.Disabled, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("graphic/hide_pass.png"), QtGui.QIcon.Active, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("graphic/show_pass.png"), QtGui.QIcon.Active, QtGui.QIcon.On)
        icon.addPixmap(QtGui.QPixmap("graphic/hide_pass.png"), QtGui.QIcon.Selected, QtGui.QIcon.Off)
        icon.addPixmap(QtGui.QPixmap("graphic/show_pass.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        self.pushButton.setIcon(icon)
        self.pushButton.setIconSize(QtCore.QSize(30, 30))
        self.pushButton.setCheckable(True)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.submit = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.submit.setFont(font)
        self.submit.setStyleSheet("background-color: transparent; color: white; border: 5px solid white; border-radius: 10px")
        self.submit.setObjectName("submit")
        self.verticalLayout.addWidget(self.submit)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.widget1 = QtWidgets.QWidget(self.tab_2)
        self.widget1.setGeometry(QtCore.QRect(10, 10, 421, 371))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: white")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.username_2 = QtWidgets.QLineEdit(self.widget1)
        self.username_2.setMinimumSize(QtCore.QSize(18, 0))
        self.username_2.setMaximumSize(QtCore.QSize(500, 30))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.username_2.setFont(font)
        self.username_2.setStyleSheet("border: 5px solid white; color: white; background-color: transparent")
        self.username_2.setText("")
        self.username_2.setObjectName("username_2")
        self.horizontalLayout_3.addWidget(self.username_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: white")
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.password_2 = QtWidgets.QLineEdit(self.widget1)
        self.password_2.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_2.setFont(font)
        self.password_2.setStyleSheet("border: 5px solid white; color: white; background-color: transparent")
        self.password_2.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_2.setObjectName("password_2")
        self.horizontalLayout_4.addWidget(self.password_2)
        self.pushButton_2 = QtWidgets.QPushButton(self.widget1)
        self.pushButton_2.setStyleSheet("background-color:transparent;\n"
"border: 3px solid white;\n"
"border-radius: 10px")
        self.pushButton_2.setText("")
        self.pushButton_2.setIcon(icon)
        self.pushButton_2.setIconSize(QtCore.QSize(30, 30))
        self.pushButton_2.setCheckable(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_4.addWidget(self.pushButton_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Tahoma")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: white")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.password_3 = QtWidgets.QLineEdit(self.widget1)
        self.password_3.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.password_3.setFont(font)
        self.password_3.setStyleSheet("border: 5px solid white; color: white; background-color: transparent")
        self.password_3.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_3.setObjectName("password_3")
        self.horizontalLayout_5.addWidget(self.password_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.submit_2 = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setFamily("Nirmala UI")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.submit_2.setFont(font)
        self.submit_2.setStyleSheet("background-color: transparent; color: white; border: 5px solid white; border-radius: 10px")
        self.submit_2.setObjectName("submit_2")
        self.verticalLayout_2.addWidget(self.submit_2)
        self.tabWidget.addTab(self.tab_2, "")

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.minimize_bt.setText(_translate("Form", "_"))
        self.close_bt.setText(_translate("Form", "X"))
        self.label.setText(_translate("Form", "PASSManager"))
        self.label_2.setText(_translate("Form", "username"))
        self.username.setPlaceholderText(_translate("Form", "Enter your username"))
        self.label_3.setText(_translate("Form", "password"))
        self.password.setPlaceholderText(_translate("Form", "Enter your password"))
        self.submit.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "login"))
        self.label_4.setText(_translate("Form", "username"))
        self.username_2.setPlaceholderText(_translate("Form", "Enter your username"))
        self.label_5.setText(_translate("Form", "password"))
        self.password_2.setPlaceholderText(_translate("Form", "Enter your password"))
        self.label_6.setText(_translate("Form", "confirm password"))
        self.password_3.setPlaceholderText(_translate("Form", "Re-Enter your password"))
        self.submit_2.setText(_translate("Form", "Submit"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "register"))
