# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowFlags(QtCore.Qt.FramelessWindowHint)
        Form.resize(722, 394)
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(10, 10, 701, 61))
        self.frame_2.setStyleSheet("background-color: rgb(35, 35, 35);\n"
"border: 5px solid black;\n"
"border-radius: 20px;\n"
"border-bottom-right-radius: 0px;\n"
"border-bottom-left-radius:0px")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.minimize_bt = QtWidgets.QPushButton(self.frame_2)
        self.minimize_bt.setGeometry(QtCore.QRect(590, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.minimize_bt.setFont(font)
        self.minimize_bt.setStyleSheet("QPushButton#minimize_bt {\n"
"    background-color: transparent;\n"
"    color: rgb(52, 107, 1);\n"
"    border: 5px solid rgb(52, 107, 1);\n"
"    border-radius: 5px\n"
"    }\n"
"QPushButton#minimize_bt::hover {\n"
"    background-color: green\n"
"    }")
        self.minimize_bt.setObjectName("minimize_bt")
        self.close_bt = QtWidgets.QPushButton(self.frame_2)
        self.close_bt.setGeometry(QtCore.QRect(640, 10, 41, 41))
        font = QtGui.QFont()
        font.setFamily("Kristen ITC")
        font.setPointSize(19)
        font.setBold(True)
        font.setWeight(75)
        self.close_bt.setFont(font)
        self.close_bt.setStyleSheet("QPushButton#close_bt { \n"
"    background-color: transparent; \n"
"    color: rgb(166, 0, 0);\n"
"     border: 5px solid rgb(166, 0, 0);\n"
"    border-radius: 5px\n"
"    }\n"
"\n"
"QPushButton#close_bt::hover {\n"
"    background-color: red;\n"
"    }")
        self.close_bt.setObjectName("close_bt")
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(110, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("Simplified Arabic")
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white;\n"
"border: 0")
        self.label.setObjectName("label")
        self.icon = QtWidgets.QLabel(self.frame_2)
        self.icon.setGeometry(QtCore.QRect(10, 0, 81, 71))
        self.icon.setStyleSheet("border:0; background-color: transparent")
        self.icon.setText("")
        self.icon.setPixmap(QtGui.QPixmap("graphic/icon.png"))
        self.icon.setScaledContents(True)
        self.icon.setWordWrap(True)
        self.icon.setObjectName("icon")
        self.accounts = QtWidgets.QTreeWidget(Form)
        self.accounts.setGeometry(QtCore.QRect(5, 71, 711, 321))
        self.accounts.setStyleSheet("""
        QTreeWidget {
                background-color: black;
                font: 75 14pt "MS Shell Dlg 2";
                }
        QTreeWidget::item{
                border: 2px solid white;
                border-radius:5px;
                background-color: rgba(255, 255, 255, 200);
                color: black;
                padding-left: 10px
                }
        QTreeWidget::item:selected{
                background-color: rgba(175, 175, 175, 100);
                border: 2px solid red
                }
        QTreeWidget::item:!selected{
                background-color:rgba(0, 0, 0, 10);
                color: white
                }""")
        self.accounts.setObjectName("accounts")
        self.accounts.setHeaderLabel('Accounts')
        font = QtGui.QFont()
        font.setFamily("Segoe UI Black")
        font.setPointSize(21)
        font.setBold(True)
        font.setWeight(75)
        self.accounts.headerItem().setFont(0, font)
        self.accounts.headerItem().setBackground(0, QtGui.QColor(191, 191, 191))
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        self.accounts.headerItem().setForeground(0, brush)
        self.add_account = QtWidgets.QPushButton(Form)
        self.add_account.setGeometry(QtCore.QRect(590, 350, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Tw Cen MT Condensed Extra Bold")
        font.setPointSize(14)
        self.add_account.setFont(font)
        self.add_account.setStyleSheet("QPushButton#add_account{\n"
"    background-color: white;\n"
"    color: black;\n"
"    border-radius: 5px\n"
"}\n"
"\n"
"QPushButton#add_account::hover{\n"
"    background-color: gray;\n"
"    }4")
        self.add_account.setObjectName("add_account")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.minimize_bt.setText(_translate("Form", "_"))
        self.close_bt.setText(_translate("Form", "X"))
        self.label.setText(_translate("Form", "PASSManager"))
        self.add_account.setText(_translate("Form", "+Add Account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
